/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gráfica.Topologias;

import Clases.*;
import Gráfica.ScreenMain;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Nazgul
 */
public class Topologia2 extends javax.swing.JFrame {

    /**
     * Creates new form Topologia1
     */
    
    public Grafo grafo;
    public Topologia2() {
        //123
        initComponents();
         ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/topología2.JPG"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(this.topología2.getWidth(), 
        topología2.getHeight(), Image.SCALE_DEFAULT));
        topología2.setIcon(icono);
            transparente();
        //poner la interfaz en el centro
        this.setLocationRelativeTo(null);
    }
    
    public void transparente(){
        //esta funcion se crea con el fin de modificar el boton a invisible
        this.siguiente.setOpaque(false);
        this.siguiente.setContentAreaFilled(false);
        this.siguiente.setBorderPainted(false);
        ImageIcon imagen_siguiente = new ImageIcon(getClass().getResource("/imagenes/siguiente.png"));
        Icon icono_siguiente = new ImageIcon(imagen_siguiente.getImage().getScaledInstance(this.siguiente.getWidth(), 
        siguiente.getHeight(), Image.SCALE_DEFAULT));
        siguiente.setIcon(icono_siguiente);
        
        this.anterior.setOpaque(false);
        this.anterior.setContentAreaFilled(false);
        this.anterior.setBorderPainted(false);
        ImageIcon imagen_anterior = new ImageIcon(getClass().getResource("/imagenes/anterior.png"));
        Icon icono_anterior = new ImageIcon(imagen_anterior.getImage().getScaledInstance(this.anterior.getWidth(), 
        anterior.getHeight(), Image.SCALE_DEFAULT));
        anterior.setIcon(icono_anterior);
        
        this.router1.setContentAreaFilled(false);
        this.router2.setOpaque(false);
        this.router2.setContentAreaFilled(false);
        this.router3.setOpaque(false);
        this.router3.setContentAreaFilled(false);
        this.router4.setOpaque(false);
        this.router4.setContentAreaFilled(false);
        this.router5.setOpaque(false);
        this.router5.setContentAreaFilled(false);
        this.router6.setOpaque(false);
        this.router6.setContentAreaFilled(false);
        this.router7.setOpaque(false);
        this.router7.setContentAreaFilled(false);
        this.router8.setOpaque(false);
        this.router8.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        router2 = new javax.swing.JButton();
        router3 = new javax.swing.JButton();
        router4 = new javax.swing.JButton();
        router5 = new javax.swing.JButton();
        router6 = new javax.swing.JButton();
        router7 = new javax.swing.JButton();
        router8 = new javax.swing.JButton();
        router1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        topología2 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        crearTabla = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        anterior = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(router2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 70, 70));
        getContentPane().add(router3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 70, 70));
        getContentPane().add(router4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 70, 70));
        getContentPane().add(router5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 70, 70));
        getContentPane().add(router6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 70, 70));
        getContentPane().add(router7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 70, 70));
        getContentPane().add(router8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 70, 70));
        getContentPane().add(router1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Topología 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 0, -1, -1));
        getContentPane().add(topología2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 669, 398));

        menu.setText("Volver al menu principal");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 210, -1));

        crearTabla.setText("crear Tabla de Enrutamiento");
        crearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTablaActionPerformed(evt);
            }
        });
        getContentPane().add(crearTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 210, 30));

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 60, 60));

        jLabel2.setText("Topología 3");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, -1, -1));

        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 70, 60));

        jLabel3.setText("Topología 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        ScreenMain menu = new ScreenMain();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_menuActionPerformed

    private void crearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTablaActionPerformed
        //está función existe con el fin de mostrar la tabla de enrutamiento
        //se crea un grao y se pone de parametro 8 ya que serán 8 routers
        grafo = new Grafo(8);

        grafo.agregarLado(0, 1, 7);
        grafo.agregarLado(0, 3, 8);
        grafo.agregarLado(1, 2, 12);
        grafo.agregarLado(2, 3, 12);
        grafo.agregarLado(2, 4, 8);
        grafo.agregarLado(2, 5, 15);
        grafo.agregarLado(2, 7, 14);
        grafo.agregarLado(4, 6, 6);
        grafo.agregarLado(5, 6, 15);
        grafo.agregarLado(6, 7, 22);

        //grafo.mostrarLados();
        VectorDistancia vt = new VectorDistancia(grafo);

        vt.inicializarMatrices();
        vt.ejecutarVector();
          TablaEnrutamientoRouter ventana = new TablaEnrutamientoRouter(vt.getMatrizDistancia(),vt.getMatrizSgteSalto());
        ventana.setVisible(true);

    }//GEN-LAST:event_crearTablaActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        Topologia3 topo3 = new Topologia3();
        topo3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        Topologia1 topo1 = new Topologia1();
        topo1.setVisible(true);
        this.dispose();
                        
    }//GEN-LAST:event_anteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Topologia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Topologia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Topologia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Topologia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Topologia2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton crearTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton menu;
    private javax.swing.JButton router1;
    private javax.swing.JButton router2;
    private javax.swing.JButton router3;
    private javax.swing.JButton router4;
    private javax.swing.JButton router5;
    private javax.swing.JButton router6;
    private javax.swing.JButton router7;
    private javax.swing.JButton router8;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel topología2;
    // End of variables declaration//GEN-END:variables
}
