/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gráfica.Topologias;

import Clases.*;
import Gráfica.*;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nazgul
 */
public class Topologia1 extends javax.swing.JFrame {

    /**
     * Creates new form Topologia1
     */
        /*DefaultTableModel modelo;   
    private int[][] distancias;
    private int[][] saltos;
    private int router = 0;
    private int tam;*/
    public Grafo grafo;
    public Topologia1() {
        initComponents();
        /*este codigo es usado para importar una imagen y almacenarlo en una 
        variable jlabel*/
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/topología1.JPG"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(this.topología1.getWidth(), 
        topología1.getHeight(), Image.SCALE_DEFAULT));
        topología1.setIcon(icono);
        //se llama a la funcion que actualizara los botones a un modo invisible
        transparente();
        //poner la interfaz en el centro
        this.setLocationRelativeTo(null);
    }
    
    public void transparente(){
        //esta funcion se crea con el fin de modificar el boton a invisible
        this.router1.setOpaque(false);
        this.router1.setContentAreaFilled(false);
        this.router2.setOpaque(false);
        this.router2.setContentAreaFilled(false);
        this.router3.setOpaque(false);
        this.router3.setContentAreaFilled(false);
        this.router4.setOpaque(false);
        this.router4.setContentAreaFilled(false);
        this.router5.setOpaque(false);
        this.router5.setContentAreaFilled(false);
        this.router6.setOpaque(false);
        this.router6.setContentAreaFilled(false);
        this.router7.setOpaque(false);
        this.router7.setContentAreaFilled(false);
        this.router8.setOpaque(false);
        this.router8.setContentAreaFilled(false);
        //------------------------------------------
        //esta funcion permite agregar el icono al boton siguiente
        this.siguiente.setOpaque(false);
        this.siguiente.setContentAreaFilled(false);
        this.siguiente.setBorderPainted(false);
        //actualizar los valores del boton siguiente para que la imagen entre en el tamaño del boton
        ImageIcon imagen_siguiente = new ImageIcon(getClass().getResource("/imagenes/siguiente.png"));
        Icon icono_siguiente = new ImageIcon(imagen_siguiente.getImage().getScaledInstance(this.siguiente.getWidth(), 
        siguiente.getHeight(), Image.SCALE_DEFAULT));
        siguiente.setIcon(icono_siguiente);
    }
    
    
    


   /* public Topologia1(int[][] distancias, int[][] saltos) {
        this.distancias = distancias;
        this.saltos = saltos;
        this.tam = distancias.length;
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Hacia router");
        modelo.addColumn("Distancia");
        modelo.addColumn("Siguiente salto");
        jTable1.setModel(modelo);
        this.llenarTabla();
    }*/
    
    /*public void llenarTabla(int num, int[][] distancias, int[][] saltos){
         this.distancias = distancias;
        this.saltos = saltos;
        this.tam = distancias.length;
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Hacia router");
        modelo.addColumn("Distancia");
        modelo.addColumn("Siguiente salto");
        jTable1.setModel(modelo);
        System.out.println(modelo.getRowCount());
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
            System.out.println(modelo.getRowCount());
        }
        String[] fila = new String[3];
        
            fila[0] = String.valueOf(num);
            fila[1] = String.valueOf(distancias[router][num]);
            fila[2] = String.valueOf(saltos[router][num]);
            modelo.addRow(fila);
        
        this.jTable1.setModel(modelo);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        router1 = new javax.swing.JButton();
        router5 = new javax.swing.JButton();
        router2 = new javax.swing.JButton();
        router6 = new javax.swing.JButton();
        router3 = new javax.swing.JButton();
        router8 = new javax.swing.JButton();
        router4 = new javax.swing.JButton();
        router7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        topología1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        router1.setBackground(new java.awt.Color(255, 255, 255));
        router1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                router1ActionPerformed(evt);
            }
        });
        getContentPane().add(router1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, 70));
        getContentPane().add(router5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 90, 60));
        getContentPane().add(router2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, 60));
        getContentPane().add(router6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 90, 60));
        getContentPane().add(router3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 90, 60));
        getContentPane().add(router8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 90, 60));
        getContentPane().add(router4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 90, 60));
        getContentPane().add(router7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 90, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Topologia 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 0, -1, -1));
        getContentPane().add(topología1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 670, 430));
        topología1.getAccessibleContext().setAccessibleName("topología1");

        jButton2.setText("Volver al menu principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 210, -1));

        jButton1.setText("crear Tabla de Enrutamiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 210, 30));

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 60, 60));

        jLabel2.setText("Topología 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void router1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_router1ActionPerformed
       // JOptionPane.showMessageDialog(null, "hola");
        grafo = new Grafo(8);
        grafo.agregarLado(0, 1, 4);
        grafo.agregarLado(0, 2, 5);
        grafo.agregarLado(1, 3, 7);
        grafo.agregarLado(2, 3, 3);
        grafo.agregarLado(2, 5, 2);
        grafo.agregarLado(3, 4, 1);
        grafo.agregarLado(3, 6, 4);
        grafo.agregarLado(4, 5, 3);
        grafo.agregarLado(5, 7, 2);
        grafo.agregarLado(7, 6, 2);
        
        
        grafo.mostrarLados();
        VectorDistancia vt = new VectorDistancia(grafo); 
        
        vt.inicializarMatrices();
        vt.ejecutarVector();
        //TablaEnrutamientoRouter ventana = new TablaEnrutamientoRouter(vt.getMatrizDistancia(),vt.getMatrizSgteSalto());
        //llenarTabla(1,vt.getMatrizDistancia(),vt.getMatrizSgteSalto());
        
    }//GEN-LAST:event_router1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//está función existe con el fin de mostrar la tabla de enrutamiento  
        grafo = new Grafo(8);
        grafo.agregarLado(0, 1, 4);
        grafo.agregarLado(0, 2, 5);
        grafo.agregarLado(1, 3, 7);
        grafo.agregarLado(2, 3, 3);
        grafo.agregarLado(2, 5, 2);
        grafo.agregarLado(3, 4, 1);
        grafo.agregarLado(3, 6, 4);
        grafo.agregarLado(4, 5, 3);
        grafo.agregarLado(5, 7, 2);
        grafo.agregarLado(7, 6, 2);
        
        
        //grafo.mostrarLados();
        VectorDistancia vt = new VectorDistancia(grafo);
        
        vt.inicializarMatrices();
        vt.ejecutarVector();
        TablaEnrutamientoRouter ventana = new TablaEnrutamientoRouter(vt.getMatrizDistancia(),vt.getMatrizSgteSalto());
        ventana.setVisible(true);
//se crea un grao y se pone de parametro 8 ya que serán 8 routers
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ScreenMain menu = new ScreenMain();
           menu.setVisible(true);
           this.dispose();
                         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
           Topologia2 topo2 = new Topologia2();
           topo2.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Topologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Topologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Topologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Topologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Topologia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton router1;
    private javax.swing.JButton router2;
    private javax.swing.JButton router3;
    private javax.swing.JButton router4;
    private javax.swing.JButton router5;
    private javax.swing.JButton router6;
    private javax.swing.JButton router7;
    private javax.swing.JButton router8;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel topología1;
    // End of variables declaration//GEN-END:variables
}
