/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gráfica;

import Clases.*;
import Gráfica.Topologias.*;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nazgul
 */
public class ScreenMain extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz1
     */
    public int cantMax;
    public Grafo grafo;
    
    public ScreenMain() {
        initComponents();
        Iniciar();
        cantMax = Integer.parseInt(cantRouter.getText()); 
        grafo = new Grafo(cantMax);
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/logo.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icono);
        logo1.setIcon(icono);
        
        
    }
    
    public void Iniciar(){
          try{
            while(true){
                String nt = JOptionPane.showInputDialog(null,"Ingrese número máximo de routers: ");  
                if (nt.isEmpty()){
                    System.out.println("No ha ingresado n° de routers");
                    JOptionPane.showMessageDialog(null, "Número máximo de routers: 9");
                }else{
                    int n = Integer.parseInt(nt);                   
                    if (n>=2 && n<10) {
                        System.out.println("Ingreso exitoso de n° routers");
                        cantRouter.setText(nt);
                        break;
                    }else if (n<2){
                        System.out.println("Ingreso fallido de n° routers");
                        JOptionPane.showMessageDialog(null, "Debe ingresar un número mayor a 1.");
                    }
                    else if (n>=10){
                        System.out.println("Ingreso fallido de n° routers");
                        JOptionPane.showMessageDialog(null, "Número máximo de routers: 9");
                    }
                        
                }
            }
        }catch(Exception ex){
            System.out.println("Ingreso cancelado de n° routers");
            JOptionPane.showMessageDialog(null, "Adiós");
            System.exit(0);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantRouter = new javax.swing.JTextField();
        Button_Añadir = new javax.swing.JButton();
        Button_GO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        topologia1 = new javax.swing.JButton();
        topologia2 = new javax.swing.JButton();
        topologia3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("N° Router máx:");

        cantRouter.setFocusable(false);
        cantRouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantRouterActionPerformed(evt);
            }
        });
        cantRouter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantRouterKeyTyped(evt);
            }
        });

        Button_Añadir.setBackground(new java.awt.Color(0, 153, 255));
        Button_Añadir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Button_Añadir.setText("Añadir Router");
        Button_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AñadirActionPerformed(evt);
            }
        });
        Button_Añadir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Button_AñadirKeyTyped(evt);
            }
        });

        Button_GO.setBackground(new java.awt.Color(0, 153, 255));
        Button_GO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Button_GO.setText("Ejecutar vector Distancia");
        Button_GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GOActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Integrantes:\n-Claudia Barrera\n-Gabriel Carmelo\n-Andy Lazo\n-Roger Vega");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Proyecto de Redes de computadoras 2020_2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Añadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Button_GO)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cantRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cantRouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_GO, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Ingresar Topología", jPanel1);

        topologia1.setBackground(new java.awt.Color(0, 153, 255));
        topologia1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topologia1.setText("Topologia1");
        topologia1.setMaximumSize(new java.awt.Dimension(140, 30));
        topologia1.setMinimumSize(new java.awt.Dimension(140, 30));
        topologia1.setPreferredSize(new java.awt.Dimension(140, 30));
        topologia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topologia1ActionPerformed(evt);
            }
        });

        topologia2.setBackground(new java.awt.Color(0, 153, 255));
        topologia2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topologia2.setText("Topologia2");
        topologia2.setMaximumSize(new java.awt.Dimension(140, 30));
        topologia2.setMinimumSize(new java.awt.Dimension(140, 30));
        topologia2.setPreferredSize(new java.awt.Dimension(140, 30));
        topologia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topologia2ActionPerformed(evt);
            }
        });

        topologia3.setBackground(new java.awt.Color(0, 153, 255));
        topologia3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topologia3.setText("Topologia3");
        topologia3.setMaximumSize(new java.awt.Dimension(140, 30));
        topologia3.setMinimumSize(new java.awt.Dimension(140, 30));
        topologia3.setPreferredSize(new java.awt.Dimension(140, 30));
        topologia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topologia3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Proyecto de Redes de computadoras 2020_2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(topologia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(topologia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(topologia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topologia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topologia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(topologia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Topologías Precargadas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantRouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantRouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantRouterActionPerformed

    private void cantRouterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantRouterKeyTyped
        if (cantRouter.getText().length() == 1) {
            evt.consume();
        }
        if (evt.getKeyChar() != '1'&& evt.getKeyChar() != '2' && evt.getKeyChar() != '3'
                && evt.getKeyChar() != '4' && evt.getKeyChar() != '4' && evt.getKeyChar() != '6' 
                && evt.getKeyChar() != '5' && evt.getKeyChar() != '8' && evt.getKeyChar() != '9'){
            evt.consume();
        }
    }//GEN-LAST:event_cantRouterKeyTyped

    private void Button_AñadirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Button_AñadirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_AñadirKeyTyped

    private void Button_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AñadirActionPerformed

        JTextField r1t = new JTextField();
        JTextField r2t = new JTextField();
        JTextField pesot = new JTextField();
        Object[] message = {
            "Ingrese los siguientes valores:\n\n",
            "",
            "Router1: ", r1t,
            "Router2: ", r2t,
            "Peso: ", pesot,
        };
        int option = JOptionPane.showConfirmDialog(null, message, "Añadiendo conexión... ", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            try{
            int r1 = Integer.parseInt(r1t.getText());
            int r2 = Integer.parseInt(r2t.getText());
            int peso = Integer.parseInt(pesot.getText());
            if ((r1>=0 && r1<=cantMax-1) && (r2>=0 && r2<=cantMax-1) && (peso>0 && peso<=999)) {
                grafo.agregarLado(r1, r2, peso);
                System.out.println("Ingreso exitoso");
            } else {
                System.out.println("Ingreso fallido");
                JOptionPane.showMessageDialog(null, "Número máximo de router "+cantMax);
                Button_AñadirActionPerformed(evt); 
            }
            }catch(Exception ex){
                System.out.println("Ingreso fallido\nBy :"+ex);
                JOptionPane.showMessageDialog(null, "Llenar los campos correctamente con solo números");
                Button_AñadirActionPerformed(evt);             
            }
        } else {
            System.out.println("Ingreso cancelado");
        }
    }//GEN-LAST:event_Button_AñadirActionPerformed

    private void Button_GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GOActionPerformed
        System.out.println("-------------------------");
        grafo.mostrarLados();
        VectorDistancia vd = new VectorDistancia(grafo);
        vd.inicializarMatrices();
        
        vd.ejecutarVector();
        System.out.println("-------------------------");
    }//GEN-LAST:event_Button_GOActionPerformed

    private void topologia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topologia1ActionPerformed
       
            //nos ayuda a ir a la ventana de, en este caso, topologiá
           Topologia1 topo1 = new Topologia1();
           topo1.setVisible(true);
           this.dispose();
           
       
    }//GEN-LAST:event_topologia1ActionPerformed

    private void topologia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topologia2ActionPerformed
        Topologia2 topo2 = new Topologia2();
           topo2.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_topologia2ActionPerformed

    private void topologia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topologia3ActionPerformed
        Topologia3 topo3 = new Topologia3();
           topo3.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_topologia3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Añadir;
    private javax.swing.JButton Button_GO;
    private javax.swing.JTextField cantRouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JButton topologia1;
    private javax.swing.JButton topologia2;
    private javax.swing.JButton topologia3;
    // End of variables declaration//GEN-END:variables
}
