/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gráfica;

import Clases.*;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nazgul
 */
public class ScreenMain extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz1
     */
    public int cantMax;
    public Grafo grafo;
    
    public ScreenMain() {
        initComponents();
        Iniciar();
        cantMax = Integer.parseInt(cantRouter.getText()); 
        grafo = new Grafo(cantMax);
    }
    
    public void Iniciar(){
          try{
            while(true){
                String nt = JOptionPane.showInputDialog(null,"Ingrese número máximo de routers: ");  
                if (nt.isEmpty()){
                    System.out.println("No ha ingresado n° de routers");
                    JOptionPane.showMessageDialog(null, "Número máximo de routers: 9");
                }else{
                    int n = Integer.parseInt(nt);                   
                    if (n>=2 && n<10) {
                        System.out.println("Ingreso exitoso de n° routers");
                        cantRouter.setText(nt);
                        break;
                    }else if (n<2){
                        System.out.println("Ingreso fallido de n° routers");
                        JOptionPane.showMessageDialog(null, "Debe ingresar un número mayor a 1.");
                    }
                    else if (n>=10){
                        System.out.println("Ingreso fallido de n° routers");
                        JOptionPane.showMessageDialog(null, "Número máximo de routers: 9");
                    }
                        
                }
            }
        }catch(Exception ex){
            System.out.println("Ingreso cancelado de n° routers");
            JOptionPane.showMessageDialog(null, "Adiós");
            System.exit(0);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantRouter = new javax.swing.JTextField();
        Button_Añadir = new javax.swing.JButton();
        Button_GO = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("N° Router máx:");

        cantRouter.setFocusable(false);
        cantRouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantRouterActionPerformed(evt);
            }
        });
        cantRouter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantRouterKeyTyped(evt);
            }
        });

        Button_Añadir.setText("Añadir");
        Button_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AñadirActionPerformed(evt);
            }
        });
        Button_Añadir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Button_AñadirKeyTyped(evt);
            }
        });

        Button_GO.setText("GO");
        Button_GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Button_Añadir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_GO))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cantRouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Añadir)
                    .addComponent(Button_GO, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar Topología", jPanel1);

        jButton2.setText("Topologia1");

        jButton3.setText("Topologia2");

        jButton4.setText("Topologia3");

        jButton5.setText("Topologia4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Topologías Precargadas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantRouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantRouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantRouterActionPerformed

    private void cantRouterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantRouterKeyTyped
        if (cantRouter.getText().length() == 1) {
            evt.consume();
        }
        if (evt.getKeyChar() != '1'&& evt.getKeyChar() != '2' && evt.getKeyChar() != '3'
                && evt.getKeyChar() != '4' && evt.getKeyChar() != '4' && evt.getKeyChar() != '6' 
                && evt.getKeyChar() != '5' && evt.getKeyChar() != '8' && evt.getKeyChar() != '9'){
            evt.consume();
        }
    }//GEN-LAST:event_cantRouterKeyTyped

    private void Button_AñadirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Button_AñadirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_AñadirKeyTyped

    private void Button_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AñadirActionPerformed

        JTextField r1t = new JTextField();
        JTextField r2t = new JTextField();
        JTextField pesot = new JTextField();
        Object[] message = {
            "Ingrese los siguientes valores:\n\n",
            "",
            "Router1: ", r1t,
            "Router2: ", r2t,
            "Peso: ", pesot,
        };
        int option = JOptionPane.showConfirmDialog(null, message, "Añadiendo conexión... ", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            try{
            int r1 = Integer.parseInt(r1t.getText());
            int r2 = Integer.parseInt(r2t.getText());
            int peso = Integer.parseInt(pesot.getText());
            if ((r1>=0 && r1<=cantMax-1) && (r2>=0 && r2<=cantMax-1) && (peso>0 && peso<=999)) {
                grafo.agregarLado(r1, r2, peso);
                System.out.println("Ingreso exitoso");
            } else {
                System.out.println("Ingreso fallido");
                JOptionPane.showMessageDialog(null, "Número máximo de router "+cantMax);
                Button_AñadirActionPerformed(evt); 
            }
            }catch(Exception ex){
                System.out.println("Ingreso fallido\nBy :"+ex);
                JOptionPane.showMessageDialog(null, "Llenar los campos correctamente con solo números");
                Button_AñadirActionPerformed(evt);             
            }
        } else {
            System.out.println("Ingreso cancelado");
        }
    }//GEN-LAST:event_Button_AñadirActionPerformed

    private void Button_GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GOActionPerformed
        System.out.println("-------------------------");
        grafo.mostrarLados();
        VectorDistancia vd = new VectorDistancia(grafo);
        vd.inicializarMatrices();
        vd.ejecutarVector();
        System.out.println("-------------------------");
    }//GEN-LAST:event_Button_GOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Añadir;
    private javax.swing.JButton Button_GO;
    private javax.swing.JTextField cantRouter;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
